# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aztx < Formula
  desc "This tool is a helper for azure-cli that leverages fzf for a nice interface to switch between subscription contexts."
  homepage "https://github.com/riweston/aztx"
  version "0.0.2"
  license "Apache"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/riweston/aztx/releases/download/0.0.2/aztx_0.0.2_darwin_amd64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "f4abd54b87af92cfcb3e6a40ab75c0d87946c1eac64b1f865c70a77684f2df77"
    end
    if Hardware::CPU.arm?
      url "https://github.com/riweston/aztx/releases/download/0.0.2/aztx_0.0.2_darwin_arm64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "1f3edad636c5d27a8e6ab26846d5ad0c5473795599318414a64ea1103e199ec2"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/riweston/aztx/releases/download/0.0.2/aztx_0.0.2_linux_amd64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "c96335b156aee2e64bf2c4109825c3ac2b339f32b91e7ce0b6c23a6bcfd4f691"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/riweston/aztx/releases/download/0.0.2/aztx_0.0.2_linux_arm64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "58c1b0f091be0fb9d7d3e40a46350a6a053de1206ad5da08e7cf1819b097aad1"
    end
  end

  depends_on "azure-cli"
  depends_on "fzf"

  def install
    bin.install "aztx"
  end
end
